import ollama
import os
from typing import Generator, List, Dict

class OllamaService:
    def __init__(self, model_name: str = "gemma2"):
        """
        Initializes the Ollama Service layer.
        :param model_name: The name of the model to use (default: gemma2)
        """
        self.model_name = model_name
        self.host = os.environ.get("OLLAMA_HOST", "http://localhost:11434")

    def _get_client(self):
        return ollama.Client(host=self.host)

    def generate_response(self, prompt: str) -> str:
        """
        Sends a single prompt to Gemma 2 and returns the complete text response.
        """
        try:
            client = self._get_client()
            response = client.generate(
                model=self.model_name,
                prompt=prompt
            )
            return response.get('response', '')
        except Exception as e:
            return f"Service Error: Direct generation failed. {str(e)}"

    def chat(self, messages: List[Dict[str, str]]) -> str:
        """
        Handles multi-turn conversational history.
        :param messages: List of dicts, e.g., [{'role': 'user', 'content': 'Hi'}]
        """
        try:
            client = self._get_client()
            response = client.chat(
                model=self.model_name,
                messages=messages
            )
            return response.get('message', {}).get('content', '')
        except Exception as e:
            return f"Service Error: Chat failed. {str(e)}"

    def stream_response(self, prompt: str) -> Generator[str, None, None]:
        """
        Streams chunks of text as they are generated by Gemma 2 (great for real-time UI/CLI).
        """
        try:
            client = self._get_client()
            stream = client.generate(
                model=self.model_name,
                prompt=prompt,
                stream=True
            )
            for chunk in stream:
                yield chunk.get('response', '')
        except Exception as e:
            yield f"\n[Service Error during stream: {str(e)}]"